CREATE DATABASE IF NOT EXISTS saas;
USE saas;
CREATE TABLE IF NOT EXISTS company(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    identify VARCHAR(10) NOT NULL,
    company VARCHAR(80) NOT NULL,
    phone VARCHAR(15),
    email VARCHAR(80),
    owner_name VARCHAR(50) NOT NULL,
    owner_last_name VARCHAR(50) NOT NULL,
    activation_code VARCHAR(32) NOT NULL
);
CREATE TABLE IF NOT EXISTS rol(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    rol VARCHAR(50) NOT NULL,
    company_id INT(4) NOT NULL,
    FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS user(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(15),
    email VARCHAR(80),
    password VARCHAR(32) NOT NULL,
    rol_id INT(4) NOT NULL,
    company_id INT(4) NOT NULL,
    FOREIGN KEY (rol_id) REFERENCES rol(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS country(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL
);
CREATE TABLE IF NOT EXISTS state(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    country_id INT(4) NOT NULL,
    name VARCHAR(60) NOT NULL,
    FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS client(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    identify VARCHAR(10) NOT NULL,
    name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(15),
    email VARCHAR(80),
    gender TINYINT NOT NULL,
    country_id INT(4) NOT NULL,
    state_id INT(4) NOT NULL,
    address VARCHAR(100),
    FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (state_id) REFERENCES state(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS provider_type(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS provider(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    identify VARCHAR(20) NOT NULL,
    company VARCHAR(80) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    email VARCHAR(80) NOT NULL,
    acount VARCHAR(50) NOT NULL,
    type_id INT(4) NOT NULL,
    company_id INT(4) NOT NULL,
    FOREIGN KEY (type_id) REFERENCES provider_type(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS category(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    company_id INT(4) NOT NULL,
    FOREIGN KEY(company_id) REFERENCES company(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS product(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(50) NOT NULL,
    bar_code VARCHAR(50) NOT NULL,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(100),
    category_id INT(4) NOT NULL,
    stock INT(6) NOT NULL,
    company_id INT(4) NOT NULL,
    FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS costs_type(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS costs_frequency(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    frequency VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS costs(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    type_id INT(4) NOT NULL,
    frequency_id INT(4) NOT NULL,
    FOREIGN KEY (type_id) REFERENCES costs_type(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (frequency_id) REFERENCES costs_frequency(id) ON DELETE CASCADE ON UPDATE CASCADE
);